language: node_js
node_js:
  - "10"

before_install:
  - npm install
  - npm install -g codecov
  - npm install -g stryker-cli

# script:
#   - node node_modules/.bin/jest --coverage
  # - npm run test

after_success:
  - codecov
  - stryker run
